# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RKUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RKUIKit

  target 'RKUIKitTests' do
    # Pods for testing
  end

end
